# Generated by Django 3.1.2 on 2020-11-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('lecturer_name', models.CharField(blank=True, default='', max_length=250, verbose_name='Lecturer')),
                ('duration', models.IntegerField(default=2, help_text='Enter duration in hours', verbose_name='Duration')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('slides_url', models.CharField(max_length=250, verbose_name='Slides Url')),
                ('is_required', models.BooleanField(default=True, verbose_name='Is Required')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
